### ISSUE TITLE
feat: 方眼表示

### ISSUE THREAD

**Issue by bicstone** [bicstone/portfolio#61]
方眼表示を実装

```css
      body {
        background-color: #fff;
        background-image: linear-gradient(
            transparent 95%,
            rgba(0, 0, 0, 0.06) 50%,
            rgba(0, 0, 0, 0.06)
          ),
          linear-gradient(
            90deg,
            transparent 95%,
            rgba(0, 0, 0, 0.06) 50%,
            rgba(0, 0, 0, 0.06)
          );
        background-size: 16px 16px;
        background-repeat: repeat;
      }
```
